name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  codspeed:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup rust toolchain
        run: rustup show

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: codspeed-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: codspeed-${{ runner.os }}-

      - name: Install cargo-codspeed
        run: cargo install cargo-codspeed@4.3.0

      - name: Build the benchmark target(s)
        run: cargo codspeed build -p rtmalloc-bench -m simulation

      - name: Run the benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: cargo codspeed run -m simulation
